server:
  port: 8092

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://db.possrnoowinerucxubpg.supabase.co:5432/postgres
    username: postgres
    password: Princeofheart@2026
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

firebase:
  service-account-path: classpath:firebase-service-account.json

swipe-service:
  url: http://localhost:8083